name: pizza-marketplace

include:
  - path: ./compose/base.yaml
  - path: ./compose/identity.yaml
  - path: ./compose/restaurant.yaml
  - path: ./compose/notification.yaml
  - path: ./compose/search.yaml
  - path: ./compose/order.yaml
  - path: ./compose/payment.yaml
  - path: ./compose/customer.yaml
