services:
  # API gateway
  traefik:
    image: traefik:v3.6
    container_name: pizza-traefik
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - backend

  # Database (identity)
  postgres-identity:
    image: postgres:17-alpine
    container_name: pizza-pg-identity
    environment:
      POSTGRES_USER: user_dev
      POSTGRES_PASSWORD: pass_dev
      POSTGRES_DB: identity_db
    volumes:
      - pg_identity:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user_dev -d identity_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - internal

  # Database (restaurant)
  postgres-restaurant:
    image: postgres:17-alpine
    container_name: pizza-pg-restaurant
    environment:
      POSTGRES_USER: user_dev
      POSTGRES_PASSWORD: pass_dev
      POSTGRES_DB: restaurant_db
    volumes:
      - pg_restaurant:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user_dev -d restaurant_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - internal

  # Database (order)
  postgres-order:
    image: postgres:17-alpine
    container_name: pizza-pg-order
    environment:
      POSTGRES_USER: user_dev
      POSTGRES_PASSWORD: pass_dev
      POSTGRES_DB: order_db
    volumes:
      - pg_order:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user_dev -d order_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - internal

  # Migrations (identity)
  migrate-identity:
    image: migrate/migrate
    depends_on:
      postgres-identity:
        condition: service_healthy
    volumes:
      - ./identity-service/internal/infrastructure/migrations:/migrations
    command:
      [
        "-path=/migrations",
        "-database=postgres://user_dev:pass_dev@postgres-identity:5432/identity_db?sslmode=disable",
        "up"
      ]
    networks:
      - internal

  # Migrations (restaurant)
  migrate-restaurant:
    image: migrate/migrate
    depends_on:
      postgres-restaurant:
        condition: service_healthy
    volumes:
      - ./restaurant-service/internal/infrastructure/migrations:/migrations
    command:
      [
        "-path=/migrations",
        "-database=postgres://user_dev:pass_dev@postgres-restaurant:5432/restaurant_db?sslmode=disable",
        "up"
      ]
    networks:
      - internal

  # Migrations (order)
  migrate-order:
    image: migrate/migrate
    depends_on:
      postgres-order:
        condition: service_healthy
    volumes:
      - ./order-service/internal/infrastructure/migrations:/migrations
    command:
      [
        "-path=/migrations",
        "-database=postgres://user_dev:pass_dev@postgres-order:5432/order_db?sslmode=disable",
        "up"
      ]
    networks:
      - internal

  # Message Broker
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: pizza-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: user_dev
      RABBITMQ_DEFAULT_PASS: pass_dev
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - internal

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: pizza-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - internal

  # Search Engine
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.9.0
    container_name: pizza-elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=false
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - internal

  # Identity Service
  identity-service:
    container_name: pizza-identity-service
    build:
      context: .
      dockerfile: identity-service/Dockerfile
      target: dev
    volumes:
      - ./identity-service:/app
    depends_on:
      postgres-identity:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
      migrate-identity:
        condition: service_completed_successfully
    env_file: identity-service/.env
    expose:
      - "8080"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.identity.rule=PathPrefix(`/auth`) || PathPrefix(`/users`)"
      - "traefik.http.routers.auth.entrypoints=web"
      - "traefik.http.services.auth.loadbalancer.server.port=8080"
      # forward-auth middleware
      - "traefik.http.middlewares.jwt.forwardauth.address=http://identity-service:8080/auth/verify"
      - "traefik.http.middlewares.jwt.forwardauth.authRequestHeaders=Authorization"
      - "traefik.http.middlewares.jwt.forwardauth.authResponseHeaders=X-User-ID,X-User-Role"
      - "traefik.docker.network=backend"
    networks:
      - backend
      - internal

  # Identity Service (worker)
  identity-worker:
    container_name: pizza-identity-worker
    build:
      context: .
      dockerfile: identity-service/Dockerfile
      target: dev
    command: ["air", "-c", ".air.worker.toml"]
    volumes:
      - ./identity-service:/app
    depends_on:
      postgres-identity:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      migrate-identity:
        condition: service_completed_successfully
    env_file: identity-service/.env
    networks:
      - internal

  # Restaurant Service
  restaurant-service:
    container_name: pizza-restaurant-service
    build:
      context: .
      dockerfile: restaurant-service/Dockerfile
      target: dev
    volumes:
      - ./restaurant-service:/app
    depends_on:
      postgres-restaurant:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
      migrate-restaurant:
        condition: service_completed_successfully
    env_file: restaurant-service/.env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.user.rule=PathPrefix(`/restaurants`)"
      - "traefik.http.routers.user.entrypoints=web"
      - "traefik.http.routers.user.middlewares=jwt@docker"
      - "traefik.http.services.user.loadbalancer.server.port=8080"
      - "traefik.docker.network=backend"
    networks:
      - backend
      - internal

  # Notification Service
  notification-service:
    container_name: pizza-notification-service
    build:
      context: .
      dockerfile: notification-service/Dockerfile
      target: dev
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
      - ./notification-service:/app
    env_file: notification-service/.env
    networks:
      - internal

  # Search Service (API)
  search-service:
    container_name: pizza-search-service
    build:
      context: .
      dockerfile: search-service/Dockerfile
      target: dev
    volumes:
      - ./search-service:/app
    depends_on:
      elasticsearch:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    env_file: search-service/.env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.search.rule=PathPrefix(`/search`)"
      - "traefik.http.routers.search.entrypoints=web"
      - "traefik.http.services.search.loadbalancer.server.port=8080"
      - "traefik.docker.network=backend"
    networks:
      - backend
      - internal

  # Search Service (worker)
  search-worker:
    container_name: pizza-search-worker
    build:
      context: .
      dockerfile: search-service/Dockerfile
      target: dev
    command: ["air", "-c", ".air.worker.toml"]
    volumes:
      - ./search-service:/app
    depends_on:
      elasticsearch:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    env_file: search-service/.env
    networks:
      - internal

  # Order Service (API)
  order-service:
    container_name: pizza-order-service
    build:
      context: .
      dockerfile: order-service/Dockerfile
      target: dev
    volumes:
      - ./order-service:/app
    depends_on:
      postgres-order:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      migrate-order:
        condition: service_completed_successfully
    env_file: order-service/.env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.order.rule=PathPrefix(`/orders`) || PathPrefix(`/cart`) || PathPrefix(`/webhooks/stripe`)"
      - "traefik.http.routers.order.entrypoints=web"
      - "traefik.http.services.order.loadbalancer.server.port=8080"
      - "traefik.docker.network=backend"
    networks:
      - backend
      - internal

  # Order Service (worker)
  order-worker:
    container_name: pizza-order-worker
    build:
      context: .
      dockerfile: order-service/Dockerfile
      target: dev
    command: ["air", "-c", ".air.worker.toml"]
    volumes:
      - ./order-service:/app
    depends_on:
      postgres-order:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      migrate-order:
        condition: service_completed_successfully
    env_file: order-service/.env
    networks:
      - internal

volumes:
  pg_identity:
  pg_restaurant:
  pg_order:
  elasticsearch_data:
  redis_data:

networks:
  backend:
    driver: bridge
  internal:
    driver: bridge
