name: pizza-marketplace

include:
  - path: ./compose/base-test.yaml
  - path: ./compose/identity-test.yaml
  - path: ./compose/restaurant-test.yaml
  - path: ./compose/search-test.yaml
  - path: ./compose/order-test.yaml
  - path: ./compose/payment-test.yaml
  - path: ./compose/customer-test.yaml
