services:
  # API gateway
  traefik:
    image: traefik:v3.0
    container_name: pizza-traefik
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - backend

  # Database (identity)
  postgres-identity:
    image: postgres:17-alpine
    container_name: pizza-pg-identity
    environment:
      POSTGRES_USER: user_dev
      POSTGRES_PASSWORD: pass_dev
      POSTGRES_DB: identity_db
    volumes:
      - pg_identity:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user_dev -d identity_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - internal

  # Database (restaurant)
  postgres-restaurant:
    image: postgres:17-alpine
    container_name: pizza-pg-restaurant
    environment:
      POSTGRES_USER: user_dev
      POSTGRES_PASSWORD: pass_dev
      POSTGRES_DB: restaurant_db
    volumes:
      - pg_restaurant:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user_dev -d restaurant_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - internal

  # Message Broker
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: pizza-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: user_dev
      RABBITMQ_DEFAULT_PASS: pass_dev
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - internal

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: pizza-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - internal

  # Search Engine
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.9.0
    container_name: pizza-elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=false
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - internal

  # Identity Service
  identity-service:
    container_name: pizza-identity-service
    build:
      context: .
      dockerfile: docker/identity-service/Dockerfile
      target: dev
    volumes:
      - ./identity-service:/app
    depends_on:
      postgres-identity:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
    env_file: identity-service/.env
    expose:
      - "8080"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.identity.rule=PathPrefix(`/auth`) || PathPrefix(`/users`)"
      - "traefik.http.routers.auth.entrypoints=web"
      - "traefik.http.services.auth.loadbalancer.server.port=8080"
      # forward-auth middleware
      - "traefik.http.middlewares.jwt.forwardauth.address=http://identity-service:8080/auth/verify"
      - "traefik.http.middlewares.jwt.forwardauth.authRequestHeaders=Authorization"
      - "traefik.http.middlewares.jwt.forwardauth.authResponseHeaders=X-User-ID,X-User-Role"
    networks:
      - backend
      - internal

  # Restaurant Service
  restaurant-service:
    container_name: pizza-restaurant-service
    build:
      context: .
      dockerfile: docker/restaurant-service/Dockerfile
      target: dev
    volumes:
      - ./restaurant-service:/app
    depends_on:
      postgres-restaurant:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
    env_file: restaurant-service/.env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.user.rule=PathPrefix(`/restaurant`)"
      - "traefik.http.routers.user.entrypoints=web"
      - "traefik.http.routers.user.middlewares=jwt@docker"
      - "traefik.http.services.user.loadbalancer.server.port=8080"
    networks:
      - backend
      - internal

  # Email Service
  email-service:
    container_name: pizza-email-service
    build:
      context: .
      dockerfile: docker/email-service/Dockerfile
      target: dev
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
      - ./email-service:/app
    env_file: email-service/.env
    networks:
      - internal

volumes:
  pg_identity:
  pg_restaurant:
  elasticsearch_data:
  redis_data:

networks:
  backend:
    driver: bridge
  internal:
    driver: bridge
    internal: true
